name: Tidal
title: Tidal
description: Domain specific language for live coding of pattern
permalink: /:categories/:title.html
baseurl: ""
markdown: kramdown
kramdown:
  default_lang: haskell
collections:
  getting_started:
  patterns:
  functions:
  videos:
  howtos:
  credits:

defaults:
  -
    scope:
      path: "getting_started"
    values:
      layout: default
  -
    scope:
      path: "patterns"
    values:
      layout: default
  -
    scope:
      path: "functions"
    values:
      layout: default
  -
    scope:
      path: "videos"
    values:
      layout: default
  -
    scope:
      path: "compositions"
    values:
      layout: default
  -
    scope:
      path: "concepts"
    values:
      layout: default
  -
    scope:
      path: "credits"
    values:
      layout: default
      theme: bibliography
